# This is a basic workflow to help you get started with Actions

name: Update package information
run-name: Update package information

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      package-file: packages.json
      commit-message: Update package info [bot]

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Generate Package Info
      env:
        # Note that GitHub Apps cannot access packages. This has to be performed via the GITHUB_TOKEN or a user PAT.
        # https://github.com/orgs/community/discussions/24636#discussioncomment-11352345
        NuGetPackageSourceCredentials_death-crab: Username=github;Password=${{ secrets.GITHUB_TOKEN }}
      run: |
        cd status
        dotnet package search --source death-crab --configfile nuget.config --verbosity detailed --format json > ${{ env.package-file }}

    - name: Push Package Info to Public Repo
      run: |
        cd status
        git add ${{ env.package-file }}
        git commit -m "${{ env.commit-message }}"
        git push
