name: Update package versions
run-name: Update status for ${{ github.event.client_payload.repository }} on ${{ github.event.client_payload.branch }}

on:
  repository_dispatch:
    types:
      - update-status

  workflow_dispatch:

jobs:
  update-build-status:
    runs-on: ubuntu-latest
    env:
      package-file: packages.json
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate package info file
      env:
        # Note that packages and containers endpoints in the GitHub API can ONLY be read using a classic PAT
        # https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#about-github-packages
        GITHUB_API_TOKEN: ${{ secrets.PACKAGE_READ_PAT }}
      run: |
        cd status
        chmod +x ./get-containers.sh
        ./get-containers.sh > ${{ env.package-file }}
        
    - name: Commit and push
      run: |
        cd status
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add build.json
        git add ${{ env.package-file }}        
        commit_message="Update build status for repository ${{ github.event.client_payload.repository }} [bot]"
        git diff --cached --quiet || (git commit -m $commit-message && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
