# This is a basic workflow to help you get started with Actions

name: Update package information
run-name: Update package information

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      package-file: packages.json
      commit-message: Update package info [bot]

    steps:
    - name: Get app token
      uses: actions/create-github-app-token@v1.11.0
      id: get-app-token
      with:
        app-id: ${{ vars.PACKAGE_READER_APP_ID }}
        private-key: ${{ secrets.PACKAGE_READER_APP_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Generate Package Info
      env:
        NuGetPackageSourceCredentials_death-crab: Username=github;Password=${{ secrets.GITHUB_TOKEN }}
      run: |
        cd status
        dotnet package search --source death-crab --configfile nuget.config --verbosity detailed --format json > ${{ env.package-file }}

    - name: Push Package Info to Public Repo
      run: |       
        git add ${{ env.package-file }}
        git commit -m ${{ env.commit-message }}
        git push
