name: Update package versions
run-name: Update status for ${{ github.event.client_payload.repository }} on ${{ github.event.client_payload.branch }}

on:
  repository_dispatch:
    types:
      - update-status

  workflow_dispatch:

jobs:
  update-build-status:
    runs-on: ubuntu-latest
    env:
      package-file: packages.json
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Package Read Token
      uses: actions/create-github-app-token@v1.11.0
      id: get-package-read-token
      with:
        app-id: ${{ env.PACKAGE_READER_APP_ID }}
        private-key: ${{ secrets.PACKAGE_READER_APP_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Generate package info file
      env:
        GITHUB_API_TOKEN: ${{ steps.get-app-token.outputs.token }}        
      run: |
        cd status
        chmod +x ./get-containers.sh
        ./get-containers.sh > ${{ env.package-file }}
        
    - name: Commit and push
      run: |
        cd status
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add build.json
        git add ${{ env.package-file }}        
        commit_message="Update build status for repository ${{ github.event.client_payload.repository }} [bot]"
        git diff --cached --quiet || (git commit -m $commit-message && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
